### ISSUE TITLE
Registering the bundle in AppKernel causes an error

### ISSUE THREAD

**Issue by Amenel** [chadyred/EasyPdfBundle#15]
Following the installation.md file instructions, I installed this bundle using `composer require chadyred/easy-pdf-bundle` then I added `new Kark\EasyPdfBundle\EasyPdfBundle()` in AppKernel.php, as copied from the instructions file.

Right after that, I cleared the cache. This is the error message

    Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "EasyPdfBundle" from namespace "Kark\EasyPdfBundle".
    Did you forget a "use" statement for another namespace? in H:\Code\ProjectX\app\AppKernel.php:24
    Stack trace:
    #0 H:\Code\ProjectX\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(396): AppKernel->registerBundles()
    #1 H:\Code\ProjectX\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
    #2 H:\Code\ProjectX\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(68): Symfony\Component\HttpKernel\Kernel->boot()
    #3 H:\Code\ProjectX\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #4 H:\Code\ProjectX\bin\console(2 in H:\Code\ProjectX\app\AppKernel.php on line 24

For all other bundles, I haven't had to use a `use` statement. Am I doing something wrong?

**Comment by mitch10593** [comment]
Try to use "chadyred/easy-pdf-bundle": "^2.1.0" in your composer.json, then composer update chadyred/easy-pdf-bundle

It has been fixed in 2.1.0 ;)

Note: you could also force dev-master to by-pass stability requirements:
composer require chadyred/easy-pdf-bundle dev-master

**Comment by chadyred** [comment]
Yes, it's fix on master, sorry for the late.

The 2.1 is the latest version, but not reference on packagist. So use the dev-master instead.
